### ISSUE TITLE
Dahdi 3.2.0 and later will not compile on Rocky Linux 9.4

### ISSUE THREAD

**Issue by walterklomp** [asterisk/dahdi-tools#21]
Compiling 3.2.0 stops at below:

make[2]: Entering directory '/usr/src/kernels/5.14.0-427.18.1.el9_4.x86_64'
  CC [M]  /usr/local/src/dahdi-linux-complete-3.2.0+3.2.0/linux/drivers/dahdi/dahdi-sysfs.o
/usr/local/src/dahdi-linux-complete-3.2.0+3.2.0/linux/drivers/dahdi/dahdi-sysfs.c:272:27: error: initialization of ‘int (*)(const struct device *, struct kobj_uevent_env *)’ from incompatible pointer type ‘int (*)(struct device *, struct kobj_uevent_env *)’ [-Werror=incompatible-pointer-types]
  272 |         .uevent         = span_uevent,
      |                           ^~~~~~~~~~~
/usr/local/src/dahdi-linux-complete-3.2.0+3.2.0/linux/drivers/dahdi/dahdi-sysfs.c:272:27: note: (near initialization for ‘spans_bus_type.uevent’)
/usr/local/src/dahdi-linux-complete-3.2.0+3.2.0/linux/drivers/dahdi/dahdi-sysfs.c:709:27: error: initialization of ‘int (*)(const struct device *, struct kobj_uevent_env *)’ from incompatible pointer type ‘int (*)(struct device *, struct kobj_uevent_env *)’ [-Werror=incompatible-pointer-types]
  709 |         .uevent         = device_uevent,
      |                           ^~~~~~~~~~~~~
/usr/local/src/dahdi-linux-complete-3.2.0+3.2.0/linux/drivers/dahdi/dahdi-sysfs.c:709:27: note: (near initialization for ‘dahdi_device_bus.uevent’)
cc1: some warnings being treated as errors

Compiling 3.4.0rc1 stops at below:
[root@hpbx4 dahdi-linux-complete-3.4.0-rc1+3.4.0-rc1]# make
make -C linux all
make[1]: Entering directory '/usr/local/src/dahdi-linux-complete-3.4.0-rc1+3.4.0-rc1/linux'
make -C drivers/dahdi/firmware firmware-loaders
make[2]: Entering directory '/usr/local/src/dahdi-linux-complete-3.4.0-rc1+3.4.0-rc1/linux/drivers/dahdi/firmware'
make[2]: Leaving directory '/usr/local/src/dahdi-linux-complete-3.4.0-rc1+3.4.0-rc1/linux/drivers/dahdi/firmware'
make -C /lib/modules/5.14.0-427.18.1.el9_4.x86_64/build M=/usr/local/src/dahdi-linux-complete-3.4.0-rc1+3.4.0-rc1/linux/drivers/dahdi DAHDI_INCLUDE=/usr/local/src/dahdi-linux-complete-3.4.0-rc1+3.4.0-rc1/linux/include DAHDI_MODULES_EXTRA=" " HOTPLUG_FIRMWARE=yes modules DAHDI_BUILD_ALL=m
make[2]: Entering directory '/usr/src/kernels/5.14.0-427.18.1.el9_4.x86_64'
  CC [M]  /usr/local/src/dahdi-linux-complete-3.4.0-rc1+3.4.0-rc1/linux/drivers/dahdi/xpp/xbus-sysfs.o
/usr/local/src/dahdi-linux-complete-3.4.0-rc1+3.4.0-rc1/linux/drivers/dahdi/xpp/xbus-sysfs.c:472:19: error: initialization of ‘int (*)(const struct device *, struct kobj_uevent_env *)’ from incompatible pointer type ‘int (*)(struct device *, struct kobj_uevent_env *)’ [-Werror=incompatible-pointer-types]
  472 |         .uevent = astribank_uevent,
      |                   ^~~~~~~~~~~~~~~~
/usr/local/src/dahdi-linux-complete-3.4.0-rc1+3.4.0-rc1/linux/drivers/dahdi/xpp/xbus-sysfs.c:472:19: note: (near initialization for ‘toplevel_bus_type.uevent’)
cc1: some warnings being treated as errors
make[4]: *** [scripts/Makefile.build:299: /usr/local/src/dahdi-linux-complete-3.4.0-rc1+3.4.0-rc1/linux/drivers/dahdi/xpp/xbus-sysfs.o] Error 1
make[3]: *** [scripts/Makefile.build:585: /usr/local/src/dahdi-linux-complete-3.4.0-rc1+3.4.0-rc1/linux/drivers/dahdi/xpp] Error 2
make[2]: *** [Makefile:1934: /usr/local/src/dahdi-linux-complete-3.4.0-rc1+3.4.0-rc1/linux/drivers/dahdi] Error 2
make[2]: Leaving directory '/usr/src/kernels/5.14.0-427.18.1.el9_4.x86_64'
make[1]: *** [Makefile:74: modules] Error 2
make[1]: Leaving directory '/usr/local/src/dahdi-linux-complete-3.4.0-rc1+3.4.0-rc1/linux'
make: *** [Makefile:9: all] Error 2

How to fix ?

**Comment by InterLinked1** [comment]
This pertains to DAHDI Linux, not DAHDI Tools, the repo in which you opened the issue.
Also, 3.2.0 is way out of support, you should try with 3.4.0.

There are some known issues with Rocky Linux and a few other systems, you can try installing using PhreakScript and it should work for you: https://github.com/InterLinked1/phreakscript
